package com.uc.caffeine.ui.theme

import androidx.compose.ui.graphics.Color

val EspressoPrimaryLight = Color(0xFF6B4B2B)
val OnEspressoPrimaryLight = Color(0xFFFFFFFF)
val EspressoPrimaryContainerLight = Color(0xFFF7DFC3)
val OnEspressoPrimaryContainerLight = Color(0xFF251406)

val EspressoSecondaryLight = Color(0xFF695847)
val OnEspressoSecondaryLight = Color(0xFFFFFFFF)
val EspressoSecondaryContainerLight = Color(0xFFF0E0CC)
val OnEspressoSecondaryContainerLight = Color(0xFF24190F)

val EspressoTertiaryLight = Color(0xFF50653F)
val OnEspressoTertiaryLight = Color(0xFFFFFFFF)
val EspressoTertiaryContainerLight = Color(0xFFD4EABC)
val OnEspressoTertiaryContainerLight = Color(0xFF122004)

val CaffeineBackgroundLight = Color(0xFFFFF8F4)
val OnCaffeineBackgroundLight = Color(0xFF201A17)
val CaffeineSurfaceLight = Color(0xFFFFF8F4)
val OnCaffeineSurfaceLight = Color(0xFF201A17)
val CaffeineSurfaceVariantLight = Color(0xFFE7DED6)
val OnCaffeineSurfaceVariantLight = Color(0xFF50453D)
val CaffeineOutlineLight = Color(0xFF84746A)
val CaffeineOutlineVariantLight = Color(0xFFD1C5BB)
val CaffeineSurfaceDimLight = Color(0xFFE8D8CF)
val CaffeineSurfaceBrightLight = Color(0xFFFFF8F4)
val CaffeineSurfaceLowestLight = Color(0xFFFFFFFF)
val CaffeineSurfaceLowLight = Color(0xFFFBF1EA)
val CaffeineSurfaceContainerLight = Color(0xFFF6EAE2)
val CaffeineSurfaceHighLight = Color(0xFFF0E1D8)
val CaffeineSurfaceHighestLight = Color(0xFFE8D7CD)
val CaffeineInverseSurfaceLight = Color(0xFF352F2B)
val CaffeineInverseOnSurfaceLight = Color(0xFFFBEFE8)
val CaffeineInversePrimaryLight = Color(0xFFDDB892)

val EspressoPrimaryDark = Color(0xFFDDB892)
val OnEspressoPrimaryDark = Color(0xFF3B2611)
val EspressoPrimaryContainerDark = Color(0xFF56391E)
val OnEspressoPrimaryContainerDark = Color(0xFFF8DFC4)

val EspressoSecondaryDark = Color(0xFFD4C0AC)
val OnEspressoSecondaryDark = Color(0xFF382B1E)
val EspressoSecondaryContainerDark = Color(0xFF4F3F31)
val OnEspressoSecondaryContainerDark = Color(0xFFF1DECA)

val EspressoTertiaryDark = Color(0xFFB8D09E)
val OnEspressoTertiaryDark = Color(0xFF243515)
val EspressoTertiaryContainerDark = Color(0xFF394D28)
val OnEspressoTertiaryContainerDark = Color(0xFFD4EABC)

val CaffeineBackgroundDark = Color(0xFF17120F)
val OnCaffeineBackgroundDark = Color(0xFFEDE0D8)
val CaffeineSurfaceDark = Color(0xFF17120F)
val OnCaffeineSurfaceDark = Color(0xFFEDE0D8)
val CaffeineSurfaceVariantDark = Color(0xFF50453D)
val OnCaffeineSurfaceVariantDark = Color(0xFFD1C5BB)
val CaffeineOutlineDark = Color(0xFF9D8C82)
val CaffeineOutlineVariantDark = Color(0xFF50453D)
val CaffeineSurfaceDimDark = Color(0xFF17120F)
val CaffeineSurfaceBrightDark = Color(0xFF413732)
val CaffeineSurfaceLowestDark = Color(0xFF120D0B)
val CaffeineSurfaceLowDark = Color(0xFF201A17)
val CaffeineSurfaceContainerDark = Color(0xFF241E1A)
val CaffeineSurfaceHighDark = Color(0xFF2F2824)
val CaffeineSurfaceHighestDark = Color(0xFF3A322E)
val CaffeineInverseSurfaceDark = Color(0xFFEDE0D8)
val CaffeineInverseOnSurfaceDark = Color(0xFF352F2B)
val CaffeineInversePrimaryDark = Color(0xFF6D4C2C)
